### ISSUE TITLE
Implement support for V2 player

### ISSUE THREAD

**Issue by glennlunder** [demozoo/cowbell#14]
V2, the music player created by [Kebby](https://github.com/kebby) and used in several intros over the years on the pc platform, does have an open source replayer and thus could be something we could look into implementing support for.

Relevant links;

https://files.scene.org/view/resources/music/utils/libv2_1.5.zip
https://github.com/kebby/fr_public/tree/master/v2
ftp://ftp.modland.com/pub/modules/V2/

**Comment by sagamusix** [comment]
Note that it's not that simple; V2 uses tons of x86 inline assembly which would not be usable with emscripten; a full rewrite to pure C++ (or a JavaScript port from scratch) would be required.

**Comment by glennlunder** [comment]
Aha! This is where my coding n00bness comes in then - I was under the impression it was pure C. If the case is that there is a lot of assembly in there that can not be emscripten'ed, then that settles it - this can't be done. I'll close the issue.
