### ISSUE TITLE
Add support for .psid file extension

### ISSUE THREAD

**Issue by glennlunder** [demozoo/cowbell#16]
To support files hosted on Modland, that carry this extension instead of .sid.

**Comment by gasman** [comment]
Cowbell itself doesn't do any recognition of file types - you throw a file at a specified player backend, and either it works or it doesn't. If the .psid files on Modland are indeed in the .sid format, then throwing them at the jsSID backend will Just Work :-)

That's useful information for when I come to hook up .sid support on Demozoo though, so thanks for the heads-up! (Now we just need to add links to some of those .psid files on Modland - looks like we don't have anything linking there right now...)
