### ISSUE TITLE
Enable OctaMED/MED file playback from Modland

### ISSUE THREAD

**Issue by glennlunder** [demozoo/cowbell#17]
On Modland, files made by the Amiga tracker OctaMED / MED has the file extensions mmd0, mmd1, mmd2 or mmd3. Each reflect a version of the file format.

These look like they are supported by OpenMPT with the default file suffix .med (see https://wiki.openmpt.org/Manual:_Module_formats) - what I would like is for the file suffixes mentioned above to also be recognized, thus allowing replay of existing links.

Examples:

https://demozoo.org/productions/tagged/octamed/

**Comment by gasman** [comment]
Fixed in https://github.com/demozoo/demozoo/commit/e1621121511e993de89b57f80e8bed10272cb565

(example: https://demozoo.org/music/27812/)
