### ISSUE TITLE
ProTracker (Amiga) ED command bug

### ISSUE THREAD

**Issue by djh0ffman** [demozoo/cowbell#18]
The ED command (delay) appears to be triggering the sample twice, once on the first frame and again X frames after. Should only trigger X frames after.

Example tune.. https://demozoo.org/music/170664/

The kick drum in channel 1 when it comes in has a command ED2 on it to give it a little delay before playing but you can hear it being triggered twice.

**Comment by HybridDog** [comment]
It also happens when playing the file with openmpt123, but not with schismtracker.
@sagamusix

**Comment by sagamusix** [comment]
The fix for another EDx-related ProTracker quirk (https://bugs.openmpt.org/view.php?id=574) interferes here... that quirk should only be applied if there is already a sample playing I guess, but in this case the kick is not playing anymore.

**Comment by djh0ffman** [comment]
Ahhh yes. In the first frame it loads the sample pointers and the sample volume into the registers which causes whatever is playing to be heard Oh and the period value. Never actually triggers a sample.

**Comment by sagamusix** [comment]
Fixed in libopenmpt [r8653](https://source.openmpt.org/browse/openmpt?op=comp&compare[]=%2F@8652&compare[]=%2F@8653), now it's up to gasman to update his build. :)
(oh, and maybe you want to switch to the default "libopenmpt" prefix when updating libopenmpt...)

**Comment by HybridDog** [comment]
Now cowbell doesn't work [there](https://demozoo.org/music/170664/)
the firefox web console tells this:
```
Successfully compiled asm.js code (loaded from cache in 18ms)  libopenmpt.js
uncaught exception: could not load memory initializer libopenmpt.js.mem  (unbekannt)
TypeError: libopenmpt._malloc is not a function[Weitere Informationen]  openmpt.min.js:2:431
	n/this.load/</< https://demozoo.org/static/productions/js/cowbell/openmpt.min.js:2:431
```

**Comment by sagamusix** [comment]
Please try clearing your cache completely - Even Ctrl+Shift+R is not enough to force the memory initializer to be reloaded from web rather than cache.

**Comment by HybridDog** [comment]
it works, thanks
