### ISSUE TITLE
broken on Safari

### ISSUE THREAD

**Issue by senf666** [demozoo/cowbell#2]
When attempting to run any of the audio files with the exception the mp3 file on https://demozoo.github.io/cowbell/ the following errors appear in the Safari console.

![screen shot 2016-05-17 at 23 53 30](https://cloud.githubusercontent.com/assets/3512672/15342129/f571b4be-1c8a-11e6-8f0a-9100c6526470.png)
![screen shot 2016-05-17 at 23 53 55](https://cloud.githubusercontent.com/assets/3512672/15342130/f5933cba-1c8a-11e6-828a-457b2d0a20d1.png)

No audio plays :(
works fine on Chrome.
Running Safari Version 9.1 (11601.5.17.1) (latest).

Implementation on DemoZoo also not working with Safari e.g.: http://demozoo.org/music/156938/

**Comment by gasman** [comment]
This turned out to be an easy fix - Safari requires you to use `webkitAudioContext` instead of `AudioContext`. Unfortunately this just reveals a new bug when playing back with libopenmpt... ("IndexSizeError: DOM Exception 1: Index or size was negative, or greater than the allowed value.")

**Comment by gasman** [comment]
OK, secondary bug now fixed in c0a845eebe7f67733bea74ead9005315ac53edca :-)
