### ISSUE TITLE
Demo page player hangs when playing SNDH and then MOD

### ISSUE THREAD

**Issue by Kabuto** [demozoo/cowbell#29]
or the other way round, and there seem to be more cases where the player hangs when playing multiple songs.

Test procedure:
* Browser: Firefox or Chrome, Windows 10
* Open the demo page: https://demozoo.github.io/cowbell/
* Select the SNDH song from the dropdown
* Hit Play --> audio plays
* Select the MOD song from the dropdown --> audio stops
* Hit Play --> the player hangs

**Comment by glennlunder** [comment]
Confirmed.
